<?php

namespace Eusebius\Filmotheque;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-05 at 16:59:38.
 */
class MediumTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Medium
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Medium;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getID
     * @todo   Implement testGetID().
     */
    public function testGetID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getMovieID
     * @todo   Implement testGetMovieID().
     */
    public function testGetMovieID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getHeight
     * @todo   Implement testGetHeight().
     */
    public function testGetHeight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getWidth
     * @todo   Implement testGetWidth().
     */
    public function testGetWidth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getQuality
     * @todo   Implement testGetQuality().
     */
    public function testGetQuality() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getComment
     * @todo   Implement testGetComment().
     */
    public function testGetComment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getShelfmark
     * @todo   Implement testGetShelfmark().
     */
    public function testGetShelfmark() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getAudio
     * @todo   Implement testGetAudio().
     */
    public function testGetAudio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getSubs
     * @todo   Implement testGetSubs().
     */
    public function testGetSubs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::updateAll
     * @todo   Implement testUpdateAll().
     */
    public function testUpdateAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::updateAudio
     * @todo   Implement testUpdateAudio().
     */
    public function testUpdateAudio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::updateSubs
     * @todo   Implement testUpdateSubs().
     */
    public function testUpdateSubs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::retrieveMovie
     * @todo   Implement testRetrieveMovie().
     */
    public function testRetrieveMovie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::getMovie
     * @todo   Implement testGetMovie().
     */
    public function testGetMovie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::setMovieIfCorrect
     * @todo   Implement testSetMovieIfCorrect().
     */
    public function testSetMovieIfCorrect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::setValues
     * @todo   Implement testSetValues().
     */
    public function testSetValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::writeAll
     * @todo   Implement testWriteAll().
     */
    public function testWriteAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Medium::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
