<?php

namespace Eusebius\Filmotheque;
require_once(__DIR__.'/../../../Eusebius/Filmotheque/Movie.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-05 at 16:59:46.
 */
class MovieTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Movie
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Movie;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::setFieldAndWait
     * @todo   Implement testSetFieldAndWait().
     */
    public function testSetFieldAndWait() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::setValues
     * @todo   Implement testSetValues().
     */
    public function testSetValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::setLastSeen
     * @todo   Implement testSetLastSeen().
     */
    public function testSetLastSeen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::writeAll
     * @todo   Implement testWriteAll().
     */
    public function testWriteAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getID
     * @todo   Implement testGetID().
     */
    public function testGetID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getIMDbID
     * @todo   Implement testGetIMDbID().
     */
    public function testGetIMDbID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getOriginalTitle
     * @todo   Implement testGetOriginalTitle().
     */
    public function testGetOriginalTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getYear
     * @todo   Implement testGetYear().
     */
    public function testGetYear() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getMakers
     * @todo   Implement testGetMakers().
     */
    public function testGetMakers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getActors
     * @todo   Implement testGetActors().
     */
    public function testGetActors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getCategories
     * @todo   Implement testGetCategories().
     */
    public function testGetCategories() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getShortlists
     * @todo   Implement testGetShortlists().
     */
    public function testGetShortlists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getRating
     * @todo   Implement testGetRating().
     */
    public function testGetRating() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getCoverFileName
     * @todo   Implement testGetCoverFileName().
     */
    public function testGetCoverFileName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getLastseen
     * @todo   Implement testGetLastseen().
     */
    public function testGetLastseen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getFormattedLastseen
     * @todo   Implement testGetFormattedLastseen().
     */
    public function testGetFormattedLastseen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::unformatDate
     * @todo   Implement testUnformatDate().
     */
    public function testUnformatDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::updateMakers
     * @todo   Implement testUpdateMakers().
     */
    public function testUpdateMakers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::updateActors
     * @todo   Implement testUpdateActors().
     */
    public function testUpdateActors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::updateCategories
     * @todo   Implement testUpdateCategories().
     */
    public function testUpdateCategories() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::updateShortlists
     * @todo   Implement testUpdateShortlists().
     */
    public function testUpdateShortlists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::updateAll
     * @todo   Implement testUpdateAll().
     */
    public function testUpdateAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::retrieveMedia
     * @todo   Implement testRetrieveMedia().
     */
    public function testRetrieveMedia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Movie::getMedia
     * @todo   Implement testGetMedia().
     */
    public function testGetMedia() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
