<?php

namespace Eusebius\Filmotheque;
require_once(__DIR__.'/../../../Eusebius/Filmotheque/User.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-08 at 15:32:28.
 */
class UserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
