<?php

namespace Eusebius\Filmotheque;
require_once(__DIR__.'/../../../Eusebius/Filmotheque/User.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-08 at 23:20:17.
 */
class UserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Eusebius\Filmotheque\User::fetchAllUsers
     * @todo   Implement testFetchAllUsers().
     */
    public function testFetchAllUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\User::getLogin
     * @todo   Implement testGetLogin().
     */
    public function testGetLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\User::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\User::getRoles
     * @todo   Implement testGetRoles().
     */
    public function testGetRoles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\User::getPermissions
     * @todo   Implement testGetPermissions().
     */
    public function testGetPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
