<?php

namespace Eusebius\Filmotheque;
require_once(__DIR__.'/../../../includes/declarations.inc.php');

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-05 at 16:59:54.
 */
class UtilTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @todo remove this decoy test case.
     */
    public function testDecoy() {
        $this->assertTrue(true);
    }

    /**
     * @covers Eusebius\Filmotheque\Util::gotoMainPage
     * @todo   Implement testGotoMainPage().
     */
    public function testGotoMainPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::isHTTPS
     * @todo   Implement testIsHTTPS().
     */
    public function testIsHTTPS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::getRequestURI
     * @todo   Implement testGetRequestURI().
     */
    public function testGetRequestURI() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::getHttpHost
     * @todo   Implement testGetHttpHost().
     */
    public function testGetHttpHost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::gotoLoginPage
     * @todo   Implement testGotoLoginPage().
     */
    public function testGotoLoginPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::debug
     * @todo   Implement testDebug().
     */
    public function testDebug() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::fatal
     * @todo   Implement testFatal().
     */
    public function testFatal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::checkChmod
     * @todo   Implement testCheckChmod().
     */
    public function testCheckChmod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::isIntString
     * @todo   Implement testIsIntString().
     */
    public function testIsIntString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::makeHiddenParameters
     * @todo   Implement testMakeHiddenParameters().
     */
    public function testMakeHiddenParameters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::getPOSTValueOrNull
     * @todo   Implement testGetPOSTValueOrNull().
     */
    public function testGetPOSTValueOrNull() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::getMovieInSession
     * @todo   Implement testGetMovieInSession().
     */
    public function testGetMovieInSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::resetMovieInSession
     * @todo   Implement testResetMovieInSession().
     */
    public function testResetMovieInSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::getMediumInSession
     * @todo   Implement testGetMediumInSession().
     */
    public function testGetMediumInSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::getDbConnection
     * @todo   Implement testGetDbConnection().
     */
    public function testGetDbConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::disconnectDB
     * @todo   Implement testDisconnectDB().
     */
    public function testDisconnectDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Eusebius\Filmotheque\Util::stripPathFromDirs
     * @todo   Implement testStripPathFromDirs().
     */
    public function testStripPathFromDirs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
