<?php

namespace Eusebius\Exceptions;

require_once(__DIR__.'/../../../includes/declarations.inc.php');

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-09 at 14:08:28.
 */
class UserNotFoundExceptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserNotFoundException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new UserNotFoundException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    /**
     * @todo remove this decoy test case.
     */
    public function testDecoy() {
        $this->assertTrue(true);
    }

}
